# Generated by Django 5.1.4 on 2025-01-03 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)])),
                ('tag', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(3)])),
                ('price', models.FloatField()),
            ],
        ),
    ]
