# taken from docs, should work. Hopefully

# services:
#   - type: web
#     plan: free
#     name: OneLastMerch
#     runtime: python
#     buildCommand: "./build.sh"
#     startCommand: "ls OneLastMerch/ && python -m gunicorn OneLastMerch/OneLastMerch.asgi:application -k uvicorn.workers.UvicornWorker"