# Generated by Django 5.1.4 on 2025-01-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_olm', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
